version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # === Development ===
  dev:
    desc: Run CLI in watch mode
    cmds:
      - bun run dev

  build:
    desc: Build library and CLI
    cmds:
      - bun run build

  build:binary:
    desc: Build standalone binary
    cmds:
      - bun run build:binary

  # === Quality Checks ===
  ci:
    desc: Run all CI checks (run before marking any task complete)
    cmds:
      - task: typecheck
      - task: lint:fix
      - task: check-ignores
      - task: duplication
      - task: file-length
      - task: check-embeddings
      - task: knip
      - task: test
      - task: test:e2e

  lint:
    desc: Run Biome linter (check only)
    cmds:
      - bun run lint

  lint:fix:
    desc: Run Biome linter and auto-fix issues
    cmds:
      - bun run lint:fix

  format:
    desc: Format code with Biome
    cmds:
      - bun run format

  typecheck:
    desc: TypeScript type checking
    cmds:
      - bun run typecheck

  duplication:
    desc: Check for code duplication
    cmds:
      - bun run duplication

  knip:
    desc: Check for dead code (unused exports, dependencies, files)
    cmds:
      - bun run knip

  file-length:
    desc: Check file length limits
    cmds:
      - ./scripts/check_file_length.sh

  check-ignores:
    desc: Check for biome-ignore comments (zero tolerance)
    cmds:
      - ./scripts/check-ignores.sh

  check-embeddings:
    desc: Verify all query strings have pre-computed embeddings
    cmds:
      - bun scripts/check-query-embeddings.ts

  generate-embeddings:
    desc: Generate embeddings for all query strings (requires OPENAI_API_KEY)
    cmds:
      - bun scripts/generate-query-embeddings.ts

  # === Testing ===
  test:
    desc: Run unit tests
    cmds:
      - bun run test

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - bun run test:watch

  test:cov:
    desc: Run tests with coverage
    cmds:
      - bun run test:coverage

  test:e2e:
    desc: Run CLI E2E tests (pass file pattern as CLI_ARGS)
    cmds:
      - bun run vitest run --config src/cli/e2e/vitest.config.ts {{.CLI_ARGS | default "src/cli/e2e/"}}

  # === Git Hooks ===
  hooks:install:
    desc: Install git hooks with lefthook
    cmds:
      - bunx lefthook install

  hooks:run:
    desc: Run pre-commit hooks manually
    cmds:
      - bunx lefthook run pre-commit

  # === Utilities ===
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist node_modules/.cache coverage

  deps:update:
    desc: Update all dependencies
    cmds:
      - bunx npm-check-updates -u
      - bun install
